# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 23:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='expire',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 3, 12, 4, 58, 56, 460760), null=True, verbose_name='Ending On'),
        ),
    ]
